using Sitecore.Data;
#pragma warning disable 1591
#pragma warning disable 0108
// ReSharper disable InconsistentNaming
// ReSharper disable MemberHidesStaticFromOuterClass
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Elision.Fragments {
	public partial struct Templates {
	    public struct Fragment
		{
			public static readonly ID TemplateId = new ID("{231F2B92-0C3A-40D6-88CB-133A1DDAFD69}");
			public const string Name = "Fragment";
		}
    }
}
namespace Elision.Fragments
{
    public partial struct Renderings {
        public partial struct Fragments
        {
            public static readonly ID Fragment = new ID("{29CE8EA8-26B3-4638-B7E7-31A76E99DAE4}");
        }
    }
}
namespace Elision.Fragments {
	public partial struct Templates {
	    public struct FragmentContainer
		{
			public static readonly ID TemplateId = new ID("{3D5238BC-8767-4AB2-AD85-C78530DDA254}");
			public const string Name = "FragmentContainer";
		}
    }
}
namespace Elision.Fragments
{
    public partial struct Renderings {
        public partial struct System
        {
            public static readonly ID FragmentContainer = new ID("{AF7A047E-C84A-4ED1-AAAE-BBF1545635DA}");
        }
    }
}
