using Sitecore.Data;
#pragma warning disable 1591
#pragma warning disable 0108
// ReSharper disable InconsistentNaming
// ReSharper disable MemberHidesStaticFromOuterClass
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Elision.Feature.Library.Fragments
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{231F2B92-0C3A-40D6-88CB-133A1DDAFD69}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/ElisionFeatureLibraryFragments/Components/Fragment</description></item>
        /// </list>
        /// </summary>
        public struct Fragment
        {
            public static readonly ID TemplateId = new ID("{231F2B92-0C3A-40D6-88CB-133A1DDAFD69}");
            public const string Name = "Fragment";

		}
    }
}
namespace Elision.Feature.Library.Fragments
{
    public partial struct Renderings
    {
        public partial struct Fragments
        {
            /// <summary>
            /// <list type="table">
            ///     <item><term>Rendering ID:</term><description>{29CE8EA8-26B3-4638-B7E7-31A76E99DAE4}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/layout/Renderings/ElisionFeatureLibraryFragments/Fragments/Fragment</description></item>
            /// </list>
            /// </summary>
            public static readonly ID Fragment = new ID("{29CE8EA8-26B3-4638-B7E7-31A76E99DAE4}");
        }
    }
}
namespace Elision.Feature.Library.Fragments
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{3D5238BC-8767-4AB2-AD85-C78530DDA254}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/ElisionFeatureLibraryFragments/Components/FragmentContainer</description></item>
        /// </list>
        /// </summary>
        public struct FragmentContainer
        {
            public static readonly ID TemplateId = new ID("{3D5238BC-8767-4AB2-AD85-C78530DDA254}");
            public const string Name = "FragmentContainer";

		}
    }
}
namespace Elision.Feature.Library.Fragments
{
    public partial struct Renderings
    {
        public partial struct Fragments
        {
            /// <summary>
            /// <list type="table">
            ///     <item><term>Rendering ID:</term><description>{AF7A047E-C84A-4ED1-AAAE-BBF1545635DA}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/layout/Renderings/ElisionFeatureLibraryFragments/Fragments/FragmentContainer</description></item>
            /// </list>
            /// </summary>
            public static readonly ID FragmentContainer = new ID("{AF7A047E-C84A-4ED1-AAAE-BBF1545635DA}");
        }
    }
}
